const data = {
  name: {
    first: [
      "Malu",
      "Fabiana",
      "Evelyn",
      "Gael",
      "Cauê",
      "Pedro",
      "Henrique",
      "Ramos",
      "Mirella",
      "Paulo",
      "Bento",
      "Otávio",
      "Sara",
      "Regina",
    ],
    middle: [
      "Ferreira",
      "Cavalcanti",
      "Cruz",
      "Melo",
      "Tereza",
      "Liz",
      "Aparício",
      "Peixoto",
      "Viana",
    ],
    last: [
      "Santos",
      "Silva",
      "Oliveira",
      "Souza",
      "Rodrigues",
      "Alves",
      "Lima",
      "Gomes",
      "Costa",
    ],
  },
  course: [
    "Administração",
    "Telecomunicações",
    "Eletrônica",
    "Administração",
    "Química",
    "Informática",
    "Petróleo e Gás",
    "Segurança do Trabalho"
  ],
  year: [
    "1",
    "2",
    "3",
  ],
  expedient: [
    "Matutino",
    "Vespertino",
  ]
};
